"""s3 table

Revision ID: 3a09e158c8f8
Revises: cbf08ceb1c8f
Create Date: 2025-01-16 22:32:25.465183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a09e158c8f8'
down_revision: Union[str, None] = 'cbf08ceb1c8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('s3',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('file_name', sa.VARCHAR(), nullable=True),
    sa.Column('file_url', sa.VARCHAR(), nullable=True),
    sa.Column('created_at', sa.DATE(), nullable=False),
    sa.Column('updated_at', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('s3')
    # ### end Alembic commands ###
